<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContractsheetsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contractsheets = [
            // Contract Sheets for CNT-2023-001-A: Main Construction Contract (Project 1)
            // Header 1: Foundation Work
            [
                'project_id' => 1,
                'contract_id' => 1,
                'sheet_dt' => '2023-01-15',
                'sheet_type' => 0, // Header
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 1,
                'sheetheader_id' => null,
                'sheet_code' => 'SHT-001-H1',
                'sheet_name' => 'Foundation Work',
                'sheet_description' => 'Foundation and basement construction for the tower',
                'sheet_notes' => 'Includes excavation, piling, and concrete foundation',
                'sheet_qty' => 1.00,
                'sheet_price' => 15000000.00,
                'sheet_grossamt' => 15000000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 1650000.00,
                'sheet_netamt' => 16650000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 16650000.00,
                'uom_id' => 22, // LOT
                'uom_code' => 'Lot',
                'sheetgroup_seqno' => 1,
                'sheet_seqno' => 1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Items for Header 1
            [
                'project_id' => 1,
                'contract_id' => 1,
                'sheet_dt' => '2023-01-15',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 1,
                'sheetheader_id' => 1,
                'sheet_code' => 'SHT-001-I1',
                'sheet_name' => 'Excavation',
                'sheet_description' => 'Site excavation and earth removal',
                'sheet_notes' => 'Depth: 15 meters',
                'sheet_qty' => 50000.00,
                'sheet_price' => 25.00,
                'sheet_grossamt' => 1250000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 137500.00,
                'sheet_netamt' => 1387500.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 1387500.00,
                'uom_id' => 11, // M3
                'uom_name' => 'Cubic Meter',
                'sheetgroup_seqno' => 1,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 1,
                'contract_id' => 1,
                'sheet_dt' => '2023-01-15',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 1,
                'sheetheader_id' => 1,
                'sheet_code' => 'SHT-001-I2',
                'sheet_name' => 'Piling Work',
                'sheet_description' => 'Bored pile installation',
                'sheet_notes' => 'Diameter: 1.2m, Depth: 30m',
                'sheet_qty' => 200.00,
                'sheet_price' => 35000.00,
                'sheet_grossamt' => 7000000.00,
                'sheet_discountrate' => 2.00,
                'sheet_discountvalue' => 140000.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 754600.00,
                'sheet_netamt' => 7614600.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 7614600.00,
                'uom_id' => 1, // PCS
                'uom_name' => 'Pieces',
                'sheetgroup_seqno' => 1,
                'sheet_seqno' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 1,
                'contract_id' => 1,
                'sheet_dt' => '2023-01-15',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 1,
                'sheetheader_id' => 1,
                'sheet_code' => 'SHT-001-I3',
                'sheet_name' => 'Foundation Concrete',
                'sheet_description' => 'Concrete pouring for foundation slab',
                'sheet_notes' => 'Grade: K-350',
                'sheet_qty' => 8000.00,
                'sheet_price' => 850.00,
                'sheet_grossamt' => 6800000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 748000.00,
                'sheet_netamt' => 7548000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 7548000.00,
                'uom_id' => 11, // M3
                'uom_name' => 'Cubic Meter',
                'sheetgroup_seqno' => 1,
                'sheet_seqno' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Header 2: Structural Work
            [
                'project_id' => 1,
                'contract_id' => 1,
                'sheet_dt' => '2023-02-01',
                'sheet_type' => 0, // Header
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 1,
                'sheetheader_id' => null,
                'sheet_code' => 'SHT-001-H2',
                'sheet_name' => 'Structural Work',
                'sheet_description' => 'Main structure construction (50 floors)',
                'sheet_notes' => 'Includes columns, beams, and slabs',
                'sheet_qty' => 1.00,
                'sheet_price' => 45000000.00,
                'sheet_grossamt' => 45000000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 4950000.00,
                'sheet_netamt' => 49950000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 49950000.00,
                'uom_id' => 22, // LOT
                'uom_code' => 'Lot',
                'sheetgroup_seqno' => 1,
                'sheet_seqno' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Items for Header 2
            [
                'project_id' => 1,
                'contract_id' => 1,
                'sheet_dt' => '2023-02-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 1,
                'sheetheader_id' => 2,
                'sheet_code' => 'SHT-001-I4',
                'sheet_name' => 'Steel Reinforcement',
                'sheet_description' => 'Rebar installation for structure',
                'sheet_notes' => 'Grade: BJTS 40',
                'sheet_qty' => 5000.00,
                'sheet_price' => 12000.00,
                'sheet_grossamt' => 60000000.00,
                'sheet_discountrate' => 3.00,
                'sheet_discountvalue' => 1800000.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 6402000.00,
                'sheet_netamt' => 64602000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 64602000.00,
                'uom_id' => 7, // TON
                'uom_name' => 'Ton',
                'sheetgroup_seqno' => 1,
                'sheet_seqno' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 1,
                'contract_id' => 1,
                'sheet_dt' => '2023-02-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 1,
                'sheetheader_id' => 2,
                'sheet_code' => 'SHT-001-I5',
                'sheet_name' => 'Structural Concrete',
                'sheet_description' => 'Concrete for columns, beams, and slabs',
                'sheet_notes' => 'Grade: K-400',
                'sheet_qty' => 25000.00,
                'sheet_price' => 950.00,
                'sheet_grossamt' => 23750000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 2612500.00,
                'sheet_netamt' => 26362500.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 26362500.00,
                'uom_id' => 11, // M3
                'uom_name' => 'Cubic Meter',
                'sheetgroup_seqno' => 1,
                'sheet_seqno' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contract Sheets for CNT-2023-001-B: Electrical Systems Installation (Project 1)
            // Header 1: Electrical Distribution
            [
                'project_id' => 1,
                'contract_id' => 2,
                'sheet_dt' => '2023-06-01',
                'sheet_type' => 0, // Header
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 2,
                'sheetheader_id' => null,
                'sheet_code' => 'SHT-002-H1',
                'sheet_name' => 'Electrical Distribution System',
                'sheet_description' => 'Main electrical distribution and wiring',
                'sheet_notes' => 'Includes main panel, sub-panels, and distribution',
                'sheet_qty' => 1.00,
                'sheet_price' => 8000000.00,
                'sheet_grossamt' => 8000000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 880000.00,
                'sheet_netamt' => 8880000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 8880000.00,
                'uom_id' => 22, // LOT
                'uom_code' => 'Lot',
                'sheetgroup_seqno' => 2,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Items for Electrical Distribution
            [
                'project_id' => 1,
                'contract_id' => 2,
                'sheet_dt' => '2023-06-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 2,
                'sheetheader_id' => 3,
                'sheet_code' => 'SHT-002-I1',
                'sheet_name' => 'Main Distribution Panel',
                'sheet_description' => 'Main electrical panel 3000A',
                'sheet_notes' => 'Brand: Schneider Electric',
                'sheet_qty' => 5.00,
                'sheet_price' => 250000.00,
                'sheet_grossamt' => 1250000.00,
                'sheet_discountrate' => 5.00,
                'sheet_discountvalue' => 62500.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 130625.00,
                'sheet_netamt' => 1318125.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 1318125.00,
                'uom_id' => 23, // UNIT
                'uom_name' => 'Unit',
                'sheetgroup_seqno' => 2,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 1,
                'contract_id' => 2,
                'sheet_dt' => '2023-06-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 2,
                'sheetheader_id' => 3,
                'sheet_code' => 'SHT-002-I2',
                'sheet_name' => 'Electrical Wiring',
                'sheet_description' => 'NYY cable installation',
                'sheet_notes' => 'Various sizes: 2.5mm - 240mm',
                'sheet_qty' => 50000.00,
                'sheet_price' => 85.00,
                'sheet_grossamt' => 4250000.00,
                'sheet_discountrate' => 2.00,
                'sheet_discountvalue' => 85000.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 458150.00,
                'sheet_netamt' => 4623150.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 4623150.00,
                'uom_id' => 14, // M
                'uom_name' => 'Meter',
                'sheetgroup_seqno' => 2,
                'sheet_seqno' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contract Sheets for CNT-2023-002-A: Villa Construction Package (Project 2)
            // Header 1: Villa Type A
            [
                'project_id' => 2,
                'contract_id' => 3,
                'sheet_dt' => '2023-03-01',
                'sheet_type' => 0, // Header
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 3,
                'sheetheader_id' => null,
                'sheet_code' => 'SHT-003-H1',
                'sheet_name' => 'Villa Type A Construction',
                'sheet_description' => 'Construction of 50 units Villa Type A (120 sqm)',
                'sheet_notes' => '2 bedrooms, eco-friendly design',
                'sheet_qty' => 50.00,
                'sheet_price' => 350000.00,
                'sheet_grossamt' => 17500000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 1925000.00,
                'sheet_netamt' => 19425000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 19425000.00,
                'uom_id' => 23, // UNIT
                'uom_name' => 'Unit',
                'sheetgroup_seqno' => 3,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Items for Villa Type A
            [
                'project_id' => 2,
                'contract_id' => 3,
                'sheet_dt' => '2023-03-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 3,
                'sheetheader_id' => 4,
                'sheet_code' => 'SHT-003-I1',
                'sheet_name' => 'Foundation & Structure',
                'sheet_description' => 'Foundation and structural work for Villa Type A',
                'sheet_notes' => 'Reinforced concrete structure',
                'sheet_qty' => 50.00,
                'sheet_price' => 120000.00,
                'sheet_grossamt' => 6000000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 660000.00,
                'sheet_netamt' => 6660000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 6660000.00,
                'uom_id' => 23, // UNIT
                'uom_name' => 'Unit',
                'sheetgroup_seqno' => 3,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'contract_id' => 3,
                'sheet_dt' => '2023-03-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 3,
                'sheetheader_id' => 4,
                'sheet_code' => 'SHT-003-I2',
                'sheet_name' => 'Finishing Work',
                'sheet_description' => 'Interior and exterior finishing',
                'sheet_notes' => 'Includes flooring, painting, fixtures',
                'sheet_qty' => 50.00,
                'sheet_price' => 180000.00,
                'sheet_grossamt' => 9000000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 990000.00,
                'sheet_netamt' => 9990000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 9990000.00,
                'uom_id' => 23, // UNIT
                'uom_name' => 'Unit',
                'sheetgroup_seqno' => 3,
                'sheet_seqno' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Header 2: Villa Type B
            [
                'project_id' => 2,
                'contract_id' => 3,
                'sheet_dt' => '2023-03-01',
                'sheet_type' => 0, // Header
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 3,
                'sheetheader_id' => null,
                'sheet_code' => 'SHT-003-H2',
                'sheet_name' => 'Villa Type B Construction',
                'sheet_description' => 'Construction of 50 units Villa Type B (180 sqm)',
                'sheet_notes' => '3 bedrooms, premium eco-friendly design',
                'sheet_qty' => 50.00,
                'sheet_price' => 550000.00,
                'sheet_grossamt' => 27500000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 3025000.00,
                'sheet_netamt' => 30525000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 30525000.00,
                'uom_id' => 23, // UNIT
                'uom_name' => 'Unit',
                'sheetgroup_seqno' => 3,
                'sheet_seqno' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Items for Villa Type B
            [
                'project_id' => 2,
                'contract_id' => 3,
                'sheet_dt' => '2023-03-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 3,
                'sheetheader_id' => 5,
                'sheet_code' => 'SHT-003-I3',
                'sheet_name' => 'Foundation & Structure',
                'sheet_description' => 'Foundation and structural work for Villa Type B',
                'sheet_notes' => 'Reinforced concrete structure with larger footprint',
                'sheet_qty' => 50.00,
                'sheet_price' => 200000.00,
                'sheet_grossamt' => 10000000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 1100000.00,
                'sheet_netamt' => 11100000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 11100000.00,
                'uom_id' => 23, // UNIT
                'uom_name' => 'Unit',
                'sheetgroup_seqno' => 3,
                'sheet_seqno' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'contract_id' => 3,
                'sheet_dt' => '2023-03-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 3,
                'sheetheader_id' => 5,
                'sheet_code' => 'SHT-003-I4',
                'sheet_name' => 'Premium Finishing Work',
                'sheet_description' => 'Premium interior and exterior finishing',
                'sheet_notes' => 'High-end materials and fixtures',
                'sheet_qty' => 50.00,
                'sheet_price' => 280000.00,
                'sheet_grossamt' => 14000000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 1540000.00,
                'sheet_netamt' => 15540000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 15540000.00,
                'uom_id' => 23, // UNIT
                'uom_name' => 'Unit',
                'sheetgroup_seqno' => 3,
                'sheet_seqno' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contract Sheets for CNT-2023-003-A: Structural Reinforcement (Project 3)
            // Header 1: Bridge Reinforcement
            [
                'project_id' => 3,
                'contract_id' => 5,
                'sheet_dt' => '2023-05-10',
                'sheet_type' => 0, // Header
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 4,
                'sheetheader_id' => null,
                'sheet_code' => 'SHT-005-H1',
                'sheet_name' => 'Bridge Structural Reinforcement',
                'sheet_description' => 'Reinforcement of main bridge structure',
                'sheet_notes' => 'Steel beams and concrete support',
                'sheet_qty' => 1.00,
                'sheet_price' => 6500000.00,
                'sheet_grossamt' => 6500000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 715000.00,
                'sheet_netamt' => 7215000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 7215000.00,
                'uom_id' => 22, // LOT
                'uom_code' => 'Lot',
                'sheetgroup_seqno' => 4,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Items for Bridge Reinforcement
            [
                'project_id' => 3,
                'contract_id' => 5,
                'sheet_dt' => '2023-05-10',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 4,
                'sheetheader_id' => 6,
                'sheet_code' => 'SHT-005-I1',
                'sheet_name' => 'Steel Beam Installation',
                'sheet_description' => 'Installation of reinforcement steel beams',
                'sheet_notes' => 'Grade: A36 structural steel',
                'sheet_qty' => 350.00,
                'sheet_price' => 15000.00,
                'sheet_grossamt' => 5250000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 577500.00,
                'sheet_netamt' => 5827500.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 5827500.00,
                'uom_id' => 7, // TON
                'uom_name' => 'Ton',
                'sheetgroup_seqno' => 4,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 3,
                'contract_id' => 5,
                'sheet_dt' => '2023-05-10',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 4,
                'sheetheader_id' => 6,
                'sheet_code' => 'SHT-005-I2',
                'sheet_name' => 'Concrete Support Work',
                'sheet_description' => 'Additional concrete support structures',
                'sheet_notes' => 'High-strength concrete K-500',
                'sheet_qty' => 500.00,
                'sheet_price' => 1200.00,
                'sheet_grossamt' => 600000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 66000.00,
                'sheet_netamt' => 666000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 666000.00,
                'uom_id' => 11, // M3
                'uom_name' => 'Cubic Meter',
                'sheetgroup_seqno' => 4,
                'sheet_seqno' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contract Sheets for CNT-2023-004-A: Smart Office Systems (Project 4)
            // Header 1: IoT Sensors
            [
                'project_id' => 4,
                'contract_id' => 7,
                'sheet_dt' => '2023-06-01',
                'sheet_type' => 0, // Header
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 5,
                'sheetheader_id' => null,
                'sheet_code' => 'SHT-007-H1',
                'sheet_name' => 'IoT Sensor Network',
                'sheet_description' => 'Installation of IoT sensors throughout the building',
                'sheet_notes' => 'Temperature, occupancy, and air quality sensors',
                'sheet_qty' => 1.00,
                'sheet_price' => 5000000.00,
                'sheet_grossamt' => 5000000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 550000.00,
                'sheet_netamt' => 5550000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 5550000.00,
                'uom_id' => 22, // LOT
                'uom_code' => 'Lot',
                'sheetgroup_seqno' => 5,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Items for IoT Sensors
            [
                'project_id' => 4,
                'contract_id' => 7,
                'sheet_dt' => '2023-06-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 5,
                'sheetheader_id' => 7,
                'sheet_code' => 'SHT-007-I1',
                'sheet_name' => 'Temperature Sensors',
                'sheet_description' => 'Wireless temperature monitoring sensors',
                'sheet_notes' => 'Brand: Honeywell',
                'sheet_qty' => 500.00,
                'sheet_price' => 2500.00,
                'sheet_grossamt' => 1250000.00,
                'sheet_discountrate' => 10.00,
                'sheet_discountvalue' => 125000.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 123750.00,
                'sheet_netamt' => 1248750.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 1248750.00,
                'uom_id' => 1, // PCS
                'uom_name' => 'Pieces',
                'sheetgroup_seqno' => 5,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 4,
                'contract_id' => 7,
                'sheet_dt' => '2023-06-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 5,
                'sheetheader_id' => 7,
                'sheet_code' => 'SHT-007-I2',
                'sheet_name' => 'Occupancy Sensors',
                'sheet_description' => 'Motion detection and occupancy sensors',
                'sheet_notes' => 'PIR technology',
                'sheet_qty' => 300.00,
                'sheet_price' => 3500.00,
                'sheet_grossamt' => 1050000.00,
                'sheet_discountrate' => 10.00,
                'sheet_discountvalue' => 105000.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 103950.00,
                'sheet_netamt' => 1048950.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 1048950.00,
                'uom_id' => 1, // PCS
                'uom_name' => 'Pieces',
                'sheetgroup_seqno' => 5,
                'sheet_seqno' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Header 2: Automated Lighting
            [
                'project_id' => 4,
                'contract_id' => 7,
                'sheet_dt' => '2023-06-01',
                'sheet_type' => 0, // Header
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 5,
                'sheetheader_id' => null,
                'sheet_code' => 'SHT-007-H2',
                'sheet_name' => 'Automated Lighting System',
                'sheet_description' => 'Smart lighting control system',
                'sheet_notes' => 'Energy-efficient LED with automated controls',
                'sheet_qty' => 1.00,
                'sheet_price' => 6000000.00,
                'sheet_grossamt' => 6000000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 660000.00,
                'sheet_netamt' => 6660000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 6660000.00,
                'uom_id' => 22, // LOT
                'uom_code' => 'Lot',
                'sheetgroup_seqno' => 5,
                'sheet_seqno' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Items for Automated Lighting
            [
                'project_id' => 4,
                'contract_id' => 7,
                'sheet_dt' => '2023-06-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 5,
                'sheetheader_id' => 8,
                'sheet_code' => 'SHT-007-I3',
                'sheet_name' => 'LED Light Fixtures',
                'sheet_description' => 'Smart LED lighting fixtures',
                'sheet_notes' => 'Dimmable, color temperature adjustable',
                'sheet_qty' => 1000.00,
                'sheet_price' => 3500.00,
                'sheet_grossamt' => 3500000.00,
                'sheet_discountrate' => 5.00,
                'sheet_discountvalue' => 175000.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 365750.00,
                'sheet_netamt' => 3690750.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 3690750.00,
                'uom_id' => 1, // PCS
                'uom_name' => 'Pieces',
                'sheetgroup_seqno' => 5,
                'sheet_seqno' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 4,
                'contract_id' => 7,
                'sheet_dt' => '2023-06-01',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 5,
                'sheetheader_id' => 8,
                'sheet_code' => 'SHT-007-I4',
                'sheet_name' => 'Lighting Control Panels',
                'sheet_description' => 'Central lighting control system',
                'sheet_notes' => 'Integrated with building management system',
                'sheet_qty' => 10.00,
                'sheet_price' => 180000.00,
                'sheet_grossamt' => 1800000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 198000.00,
                'sheet_netamt' => 1998000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 1998000.00,
                'uom_id' => 23, // UNIT
                'uom_name' => 'Unit',
                'sheetgroup_seqno' => 5,
                'sheet_seqno' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contract Sheets for CNT-2023-005-A: Park Infrastructure (Project 5)
            // Header 1: Walking Trails
            [
                'project_id' => 5,
                'contract_id' => 9,
                'sheet_dt' => '2023-04-15',
                'sheet_type' => 0, // Header
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 6,
                'sheetheader_id' => null,
                'sheet_code' => 'SHT-009-H1',
                'sheet_name' => 'Walking Trails Development',
                'sheet_description' => 'Construction of walking and jogging trails',
                'sheet_notes' => 'Total length: 5 km',
                'sheet_qty' => 5000.00,
                'sheet_price' => 1500.00,
                'sheet_grossamt' => 7500000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 825000.00,
                'sheet_netamt' => 8325000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 8325000.00,
                'uom_id' => 14, // M
                'uom_name' => 'Meter',
                'sheetgroup_seqno' => 6,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Items for Walking Trails
            [
                'project_id' => 5,
                'contract_id' => 9,
                'sheet_dt' => '2023-04-15',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 6,
                'sheetheader_id' => 9,
                'sheet_code' => 'SHT-009-I1',
                'sheet_name' => 'Trail Paving',
                'sheet_description' => 'Paving with eco-friendly materials',
                'sheet_notes' => 'Permeable paving stones',
                'sheet_qty' => 5000.00,
                'sheet_price' => 850.00,
                'sheet_grossamt' => 4250000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 467500.00,
                'sheet_netamt' => 4717500.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 4717500.00,
                'uom_id' => 14, // M
                'uom_name' => 'Meter',
                'sheetgroup_seqno' => 6,
                'sheet_seqno' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 5,
                'contract_id' => 9,
                'sheet_dt' => '2023-04-15',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 6,
                'sheetheader_id' => 9,
                'sheet_code' => 'SHT-009-I2',
                'sheet_name' => 'Trail Lighting',
                'sheet_description' => 'Solar-powered pathway lighting',
                'sheet_notes' => 'LED lights with motion sensors',
                'sheet_qty' => 200.00,
                'sheet_price' => 4500.00,
                'sheet_grossamt' => 900000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 99000.00,
                'sheet_netamt' => 999000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 999000.00,
                'uom_id' => 1, // PCS
                'uom_name' => 'Pieces',
                'sheetgroup_seqno' => 6,
                'sheet_seqno' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Header 2: Playground
            [
                'project_id' => 5,
                'contract_id' => 9,
                'sheet_dt' => '2023-04-15',
                'sheet_type' => 0, // Header
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 6,
                'sheetheader_id' => null,
                'sheet_code' => 'SHT-009-H2',
                'sheet_name' => 'Children Playground',
                'sheet_description' => 'Construction of children play area',
                'sheet_notes' => 'Safe and eco-friendly playground equipment',
                'sheet_qty' => 1.00,
                'sheet_price' => 2500000.00,
                'sheet_grossamt' => 2500000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 275000.00,
                'sheet_netamt' => 2775000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 2775000.00,
                'uom_id' => 22, // LOT
                'uom_code' => 'Lot',
                'sheetgroup_seqno' => 6,
                'sheet_seqno' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Items for Playground
            [
                'project_id' => 5,
                'contract_id' => 9,
                'sheet_dt' => '2023-04-15',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 6,
                'sheetheader_id' => 10,
                'sheet_code' => 'SHT-009-I3',
                'sheet_name' => 'Play Equipment',
                'sheet_description' => 'Swings, slides, and climbing structures',
                'sheet_notes' => 'Certified safe for children',
                'sheet_qty' => 15.00,
                'sheet_price' => 85000.00,
                'sheet_grossamt' => 1275000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 140250.00,
                'sheet_netamt' => 1415250.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 1415250.00,
                'uom_id' => 1, // PCS
                'uom_name' => 'Pieces',
                'sheetgroup_seqno' => 6,
                'sheet_seqno' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 5,
                'contract_id' => 9,
                'sheet_dt' => '2023-04-15',
                'sheet_type' => 1, // Item
                'sheetgroup_type' => 0,
                'sheetgroup_id' => 6,
                'sheetheader_id' => 10,
                'sheet_code' => 'SHT-009-I4',
                'sheet_name' => 'Safety Surfacing',
                'sheet_description' => 'Rubber safety surfacing for playground',
                'sheet_notes' => 'Impact-absorbing material',
                'sheet_qty' => 500.00,
                'sheet_price' => 1200.00,
                'sheet_grossamt' => 600000.00,
                'sheet_discountrate' => 0.00,
                'sheet_discountvalue' => 0.00,
                'sheet_taxrate' => 11.00,
                'sheet_taxvalue' => 66000.00,
                'sheet_netamt' => 666000.00,
                'sheet_grossamt2' => 0.00,
                'sheet_netamt2' => 0.00,
                'sheet_realamt' => 666000.00,
                'uom_id' => 17, // M2
                'uom_name' => 'Square Meter',
                'sheetgroup_seqno' => 6,
                'sheet_seqno' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('contractsheets')->insert($contractsheets);
    }
}
