<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContractsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contracts = [
            // Contracts for PRJ-2023-001: Skyline Tower Construction
            [
                'project_id' => 1,
                'contract_name' => 'Main Construction Contract',
                'contract_description' => 'Primary construction contract for the 50-story residential tower including foundation, structure, and finishing.',
                'contract_number' => 'CNT-2023-001-A',
                'contract_pic' => 'John Anderson',
                'contractstatus_id' => 1,
                'contract_progress' => 65,
                'contract_dt' => '2023-01-10',
                'contract_startdt' => '2023-01-15',
                'contract_enddt' => '2025-06-30',
                'contract_amount' => 85000000.00,
                'contract_payment' => 55250000.00,
                'contract_payment_dt' => '2024-11-15',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 1,
                'contract_name' => 'Electrical Systems Installation',
                'contract_description' => 'Installation of electrical systems, wiring, and backup generators for the tower.',
                'contract_number' => 'CNT-2023-001-B',
                'contract_pic' => 'Michael Torres',
                'contractstatus_id' => 1,
                'contract_progress' => 45,
                'contract_dt' => '2023-02-01',
                'contract_startdt' => '2023-06-01',
                'contract_enddt' => '2025-05-15',
                'contract_amount' => 12500000.00,
                'contract_payment' => 5625000.00,
                'contract_payment_dt' => '2024-10-20',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-002: Green Valley Estate Phase 1
            [
                'project_id' => 2,
                'contract_name' => 'Villa Construction Package',
                'contract_description' => 'Construction of 100 luxury villas with eco-friendly materials and sustainable design.',
                'contract_number' => 'CNT-2023-002-A',
                'contract_pic' => 'Sarah Jenkins',
                'contractstatus_id' => 1,
                'contract_progress' => 78,
                'contract_dt' => '2023-02-15',
                'contract_startdt' => '2023-03-01',
                'contract_enddt' => '2024-12-15',
                'contract_amount' => 45000000.00,
                'contract_payment' => 35100000.00,
                'contract_payment_dt' => '2024-11-25',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 2,
                'contract_name' => 'Solar Panel Installation',
                'contract_description' => 'Installation of solar panels on all villa rooftops for renewable energy.',
                'contract_number' => 'CNT-2023-002-B',
                'contract_pic' => 'David Green',
                'contractstatus_id' => 1,
                'contract_progress' => 60,
                'contract_dt' => '2023-03-20',
                'contract_startdt' => '2023-08-01',
                'contract_enddt' => '2024-11-30',
                'contract_amount' => 8500000.00,
                'contract_payment' => 5100000.00,
                'contract_payment_dt' => '2024-10-15',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-003: Harbor Bridge Maintenance
            [
                'project_id' => 3,
                'contract_name' => 'Structural Reinforcement',
                'contract_description' => 'Reinforcement of bridge structure including steel beams and concrete support.',
                'contract_number' => 'CNT-2023-003-A',
                'contract_pic' => 'Michael Ross',
                'contractstatus_id' => 2,
                'contract_progress' => 100,
                'contract_dt' => '2023-04-25',
                'contract_startdt' => '2023-05-10',
                'contract_enddt' => '2023-11-20',
                'contract_amount' => 6500000.00,
                'contract_payment' => 6500000.00,
                'contract_payment_dt' => '2023-12-05',
                'contract_payment_status' => 'Paid',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 3,
                'contract_name' => 'Bridge Repainting',
                'contract_description' => 'Complete repainting of the harbor bridge with anti-corrosion coating.',
                'contract_number' => 'CNT-2023-003-B',
                'contract_pic' => 'Robert Brown',
                'contractstatus_id' => 2,
                'contract_progress' => 100,
                'contract_dt' => '2023-05-01',
                'contract_startdt' => '2023-07-01',
                'contract_enddt' => '2023-11-15',
                'contract_amount' => 2800000.00,
                'contract_payment' => 2800000.00,
                'contract_payment_dt' => '2023-11-30',
                'contract_payment_status' => 'Paid',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-004: Tech Hub HQ Renovation
            [
                'project_id' => 4,
                'contract_name' => 'Smart Office Systems',
                'contract_description' => 'Installation of smart office solutions including IoT sensors, automated lighting, and climate control.',
                'contract_number' => 'CNT-2023-004-A',
                'contract_pic' => 'Emily Chen',
                'contractstatus_id' => 1,
                'contract_progress' => 85,
                'contract_dt' => '2023-05-20',
                'contract_startdt' => '2023-06-01',
                'contract_enddt' => '2024-02-28',
                'contract_amount' => 15000000.00,
                'contract_payment' => 12750000.00,
                'contract_payment_dt' => '2024-11-20',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 4,
                'contract_name' => 'Interior Renovation',
                'contract_description' => 'Complete interior renovation including modern workspaces, meeting rooms, and collaboration areas.',
                'contract_number' => 'CNT-2023-004-B',
                'contract_pic' => 'Jennifer Liu',
                'contractstatus_id' => 1,
                'contract_progress' => 90,
                'contract_dt' => '2023-05-25',
                'contract_startdt' => '2023-06-15',
                'contract_enddt' => '2024-02-15',
                'contract_amount' => 8500000.00,
                'contract_payment' => 7650000.00,
                'contract_payment_dt' => '2024-11-28',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-005: Riverfront Park Development
            [
                'project_id' => 5,
                'contract_name' => 'Park Infrastructure',
                'contract_description' => 'Development of walking trails, playgrounds, and landscaping for the riverfront park.',
                'contract_number' => 'CNT-2023-005-A',
                'contract_pic' => 'David Wilson',
                'contractstatus_id' => 1,
                'contract_progress' => 70,
                'contract_dt' => '2023-04-01',
                'contract_startdt' => '2023-04-15',
                'contract_enddt' => '2024-05-01',
                'contract_amount' => 5500000.00,
                'contract_payment' => 3850000.00,
                'contract_payment_dt' => '2024-11-10',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 5,
                'contract_name' => 'Community Center Construction',
                'contract_description' => 'Construction of a multi-purpose community center with event spaces and facilities.',
                'contract_number' => 'CNT-2023-005-B',
                'contract_pic' => 'Patricia Moore',
                'contractstatus_id' => 1,
                'contract_progress' => 55,
                'contract_dt' => '2023-04-10',
                'contract_startdt' => '2023-07-01',
                'contract_enddt' => '2024-04-30',
                'contract_amount' => 7200000.00,
                'contract_payment' => 3960000.00,
                'contract_payment_dt' => '2024-10-25',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-006: Solar Farm Alpha
            [
                'project_id' => 6,
                'contract_name' => 'Solar Panel Installation',
                'contract_description' => 'Installation of solar panels for 50MW power generation capacity.',
                'contract_number' => 'CNT-2023-006-A',
                'contract_pic' => 'Jessica Lee',
                'contractstatus_id' => 2,
                'contract_progress' => 100,
                'contract_dt' => '2023-02-10',
                'contract_startdt' => '2023-02-20',
                'contract_enddt' => '2023-12-31',
                'contract_amount' => 35000000.00,
                'contract_payment' => 35000000.00,
                'contract_payment_dt' => '2024-01-15',
                'contract_payment_status' => 'Paid',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 6,
                'contract_name' => 'Grid Connection & Infrastructure',
                'contract_description' => 'Connection to power grid and installation of transformers and distribution systems.',
                'contract_number' => 'CNT-2023-006-B',
                'contract_pic' => 'Mark Stevens',
                'contractstatus_id' => 2,
                'contract_progress' => 100,
                'contract_dt' => '2023-02-15',
                'contract_startdt' => '2023-05-01',
                'contract_enddt' => '2023-12-20',
                'contract_amount' => 8500000.00,
                'contract_payment' => 8500000.00,
                'contract_payment_dt' => '2024-01-10',
                'contract_payment_status' => 'Paid',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-007: Highway 101 Expansion
            [
                'project_id' => 7,
                'contract_name' => 'Highway Widening Phase 1',
                'contract_description' => 'Widening of Highway 101 northern section to add two new lanes.',
                'contract_number' => 'CNT-2023-007-A',
                'contract_pic' => 'Robert Taylor',
                'contractstatus_id' => 1,
                'contract_progress' => 35,
                'contract_dt' => '2023-06-15',
                'contract_startdt' => '2023-07-01',
                'contract_enddt' => '2025-12-31',
                'contract_amount' => 125000000.00,
                'contract_payment' => 43750000.00,
                'contract_payment_dt' => '2024-11-30',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 7,
                'contract_name' => 'Bridge Construction',
                'contract_description' => 'Construction of new highway bridges and overpasses.',
                'contract_number' => 'CNT-2023-007-B',
                'contract_pic' => 'Christopher Davis',
                'contractstatus_id' => 1,
                'contract_progress' => 25,
                'contract_dt' => '2023-06-20',
                'contract_startdt' => '2023-09-01',
                'contract_enddt' => '2025-10-31',
                'contract_amount' => 45000000.00,
                'contract_payment' => 11250000.00,
                'contract_payment_dt' => '2024-10-15',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-008: Metro Station North
            [
                'project_id' => 8,
                'contract_name' => 'Underground Excavation',
                'contract_description' => 'Excavation and tunnel construction for the underground metro station.',
                'contract_number' => 'CNT-2023-008-A',
                'contract_pic' => 'Amanda White',
                'contractstatus_id' => 1,
                'contract_progress' => 40,
                'contract_dt' => '2023-07-30',
                'contract_startdt' => '2023-08-15',
                'contract_enddt' => '2026-03-30',
                'contract_amount' => 95000000.00,
                'contract_payment' => 38000000.00,
                'contract_payment_dt' => '2024-11-15',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 8,
                'contract_name' => 'Station Facilities & Systems',
                'contract_description' => 'Installation of platform facilities, ticketing systems, and ventilation.',
                'contract_number' => 'CNT-2023-008-B',
                'contract_pic' => 'Richard Martinez',
                'contractstatus_id' => 1,
                'contract_progress' => 20,
                'contract_dt' => '2023-08-10',
                'contract_startdt' => '2024-01-01',
                'contract_enddt' => '2026-02-28',
                'contract_amount' => 35000000.00,
                'contract_payment' => 7000000.00,
                'contract_payment_dt' => '2024-09-20',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-009: Ocean View Apartments
            [
                'project_id' => 9,
                'contract_name' => 'Apartment Complex Construction',
                'contract_description' => 'Construction of 200 seaside apartment units with ocean views.',
                'contract_number' => 'CNT-2023-009-A',
                'contract_pic' => 'Daniel Martin',
                'contractstatus_id' => 1,
                'contract_progress' => 50,
                'contract_dt' => '2023-08-20',
                'contract_startdt' => '2023-09-01',
                'contract_enddt' => '2025-05-15',
                'contract_amount' => 75000000.00,
                'contract_payment' => 37500000.00,
                'contract_payment_dt' => '2024-11-10',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 9,
                'contract_name' => 'Amenities & Landscaping',
                'contract_description' => 'Development of swimming pools, gym facilities, and coastal landscaping.',
                'contract_number' => 'CNT-2023-009-B',
                'contract_pic' => 'Lisa Anderson',
                'contractstatus_id' => 1,
                'contract_progress' => 30,
                'contract_dt' => '2023-09-05',
                'contract_startdt' => '2024-01-01',
                'contract_enddt' => '2025-04-30',
                'contract_amount' => 12000000.00,
                'contract_payment' => 3600000.00,
                'contract_payment_dt' => '2024-10-05',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-010: Industrial Warehouse A
            [
                'project_id' => 10,
                'contract_name' => 'Warehouse Construction',
                'contract_description' => 'Construction of large-scale logistics warehouse with loading docks.',
                'contract_number' => 'CNT-2023-010-A',
                'contract_pic' => 'Thomas Clark',
                'contractstatus_id' => 1,
                'contract_progress' => 75,
                'contract_dt' => '2023-09-25',
                'contract_startdt' => '2023-10-10',
                'contract_enddt' => '2024-08-20',
                'contract_amount' => 18000000.00,
                'contract_payment' => 13500000.00,
                'contract_payment_dt' => '2024-11-20',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 10,
                'contract_name' => 'Automated Systems Installation',
                'contract_description' => 'Installation of automated storage and retrieval systems.',
                'contract_number' => 'CNT-2023-010-B',
                'contract_pic' => 'William Johnson',
                'contractstatus_id' => 1,
                'contract_progress' => 60,
                'contract_dt' => '2023-10-01',
                'contract_startdt' => '2024-02-01',
                'contract_enddt' => '2024-08-15',
                'contract_amount' => 9500000.00,
                'contract_payment' => 5700000.00,
                'contract_payment_dt' => '2024-10-30',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-011: Community Hospital Wing
            [
                'project_id' => 11,
                'contract_name' => 'Pediatric Wing Construction',
                'contract_description' => 'Construction of new pediatric care wing with specialized facilities.',
                'contract_number' => 'CNT-2023-011-A',
                'contract_pic' => 'Karen Lewis',
                'contractstatus_id' => 1,
                'contract_progress' => 55,
                'contract_dt' => '2023-10-15',
                'contract_startdt' => '2023-11-01',
                'contract_enddt' => '2025-01-30',
                'contract_amount' => 42000000.00,
                'contract_payment' => 23100000.00,
                'contract_payment_dt' => '2024-11-25',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 11,
                'contract_name' => 'Medical Equipment Installation',
                'contract_description' => 'Installation of advanced medical equipment and monitoring systems.',
                'contract_number' => 'CNT-2023-011-B',
                'contract_pic' => 'Dr. Susan Parker',
                'contractstatus_id' => 1,
                'contract_progress' => 35,
                'contract_dt' => '2023-10-20',
                'contract_startdt' => '2024-06-01',
                'contract_enddt' => '2025-01-15',
                'contract_amount' => 15000000.00,
                'contract_payment' => 5250000.00,
                'contract_payment_dt' => '2024-10-10',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-012: University Library Modernization
            [
                'project_id' => 12,
                'contract_name' => 'Digital Archive System',
                'contract_description' => 'Implementation of digital archive system and database infrastructure.',
                'contract_number' => 'CNT-2023-012-A',
                'contract_pic' => 'Brian Walker',
                'contractstatus_id' => 1,
                'contract_progress' => 80,
                'contract_dt' => '2023-05-10',
                'contract_startdt' => '2023-05-20',
                'contract_enddt' => '2024-04-15',
                'contract_amount' => 6500000.00,
                'contract_payment' => 5200000.00,
                'contract_payment_dt' => '2024-11-15',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 12,
                'contract_name' => 'Study Pods & Furniture',
                'contract_description' => 'Installation of modern study pods, furniture, and collaborative spaces.',
                'contract_number' => 'CNT-2023-012-B',
                'contract_pic' => 'Michelle Thompson',
                'contractstatus_id' => 1,
                'contract_progress' => 85,
                'contract_dt' => '2023-05-15',
                'contract_startdt' => '2023-08-01',
                'contract_enddt' => '2024-03-31',
                'contract_amount' => 3500000.00,
                'contract_payment' => 2975000.00,
                'contract_payment_dt' => '2024-11-20',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-013: Airport Terminal 3
            [
                'project_id' => 13,
                'contract_name' => 'Terminal Building Construction',
                'contract_description' => 'Construction of new international terminal building with 50 gates.',
                'contract_number' => 'CNT-2023-013-A',
                'contract_pic' => 'Steven Hall',
                'contractstatus_id' => 1,
                'contract_progress' => 30,
                'contract_dt' => '2022-12-20',
                'contract_startdt' => '2023-01-10',
                'contract_enddt' => '2027-12-31',
                'contract_amount' => 450000000.00,
                'contract_payment' => 135000000.00,
                'contract_payment_dt' => '2024-11-30',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 13,
                'contract_name' => 'Baggage Handling System',
                'contract_description' => 'Installation of automated baggage handling and security screening systems.',
                'contract_number' => 'CNT-2023-013-B',
                'contract_pic' => 'George Wilson',
                'contractstatus_id' => 1,
                'contract_progress' => 15,
                'contract_dt' => '2023-01-05',
                'contract_startdt' => '2024-06-01',
                'contract_enddt' => '2027-10-31',
                'contract_amount' => 85000000.00,
                'contract_payment' => 12750000.00,
                'contract_payment_dt' => '2024-09-15',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-014: Data Center X
            [
                'project_id' => 14,
                'contract_name' => 'Data Center Construction',
                'contract_description' => 'Construction of high-security data center facility with redundant systems.',
                'contract_number' => 'CNT-2023-014-A',
                'contract_pic' => 'Laura Allen',
                'contractstatus_id' => 1,
                'contract_progress' => 90,
                'contract_dt' => '2023-03-05',
                'contract_startdt' => '2023-03-15',
                'contract_enddt' => '2024-09-30',
                'contract_amount' => 65000000.00,
                'contract_payment' => 58500000.00,
                'contract_payment_dt' => '2024-11-28',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 14,
                'contract_name' => 'Cooling & Power Systems',
                'contract_description' => 'Installation of advanced cooling systems and backup power infrastructure.',
                'contract_number' => 'CNT-2023-014-B',
                'contract_pic' => 'Andrew Mitchell',
                'contractstatus_id' => 1,
                'contract_progress' => 85,
                'contract_dt' => '2023-03-10',
                'contract_startdt' => '2023-06-01',
                'contract_enddt' => '2024-09-15',
                'contract_amount' => 28000000.00,
                'contract_payment' => 23800000.00,
                'contract_payment_dt' => '2024-11-10',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-015: Suburban Housing Phase 1
            [
                'project_id' => 15,
                'contract_name' => 'Affordable Housing Units',
                'contract_description' => 'Construction of 150 affordable housing units in suburban area.',
                'contract_number' => 'CNT-2023-015-A',
                'contract_pic' => 'Kevin Young',
                'contractstatus_id' => 1,
                'contract_progress' => 65,
                'contract_dt' => '2023-06-10',
                'contract_startdt' => '2023-06-20',
                'contract_enddt' => '2024-11-30',
                'contract_amount' => 32000000.00,
                'contract_payment' => 20800000.00,
                'contract_payment_dt' => '2024-11-15',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 15,
                'contract_name' => 'Community Infrastructure',
                'contract_description' => 'Development of roads, utilities, and common areas for the housing community.',
                'contract_number' => 'CNT-2023-015-B',
                'contract_pic' => 'Sandra Rodriguez',
                'contractstatus_id' => 1,
                'contract_progress' => 70,
                'contract_dt' => '2023-06-15',
                'contract_startdt' => '2023-07-01',
                'contract_enddt' => '2024-10-31',
                'contract_amount' => 8500000.00,
                'contract_payment' => 5950000.00,
                'contract_payment_dt' => '2024-11-05',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-016: Downtown Plaza Revamp
            [
                'project_id' => 16,
                'contract_name' => 'Plaza Redesign & Construction',
                'contract_description' => 'Redesigning central plaza with new fountains, seating areas, and landscaping.',
                'contract_number' => 'CNT-2023-016-A',
                'contract_pic' => 'Nancy King',
                'contractstatus_id' => 2,
                'contract_progress' => 100,
                'contract_dt' => '2023-03-20',
                'contract_startdt' => '2023-04-01',
                'contract_enddt' => '2023-10-31',
                'contract_amount' => 4500000.00,
                'contract_payment' => 4500000.00,
                'contract_payment_dt' => '2023-11-15',
                'contract_payment_status' => 'Paid',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 16,
                'contract_name' => 'Lighting & Smart Features',
                'contract_description' => 'Installation of decorative lighting and smart city features.',
                'contract_number' => 'CNT-2023-016-B',
                'contract_pic' => 'Paul Harris',
                'contractstatus_id' => 2,
                'contract_progress' => 100,
                'contract_dt' => '2023-03-25',
                'contract_startdt' => '2023-06-01',
                'contract_enddt' => '2023-10-25',
                'contract_amount' => 1800000.00,
                'contract_payment' => 1800000.00,
                'contract_payment_dt' => '2023-11-10',
                'contract_payment_status' => 'Paid',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-017: Wind Turbine Field
            [
                'project_id' => 17,
                'contract_name' => 'Wind Turbine Installation',
                'contract_description' => 'Installation of 20 wind turbines for renewable energy generation.',
                'contract_number' => 'CNT-2023-017-A',
                'contract_pic' => 'Gary Wright',
                'contractstatus_id' => 2,
                'contract_progress' => 100,
                'contract_dt' => '2023-02-01',
                'contract_startdt' => '2023-02-10',
                'contract_enddt' => '2023-11-15',
                'contract_amount' => 28000000.00,
                'contract_payment' => 28000000.00,
                'contract_payment_dt' => '2023-12-01',
                'contract_payment_status' => 'Paid',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 17,
                'contract_name' => 'Grid Integration & Monitoring',
                'contract_description' => 'Integration with power grid and installation of monitoring systems.',
                'contract_number' => 'CNT-2023-017-B',
                'contract_pic' => 'Elizabeth Cooper',
                'contractstatus_id' => 2,
                'contract_progress' => 100,
                'contract_dt' => '2023-02-05',
                'contract_startdt' => '2023-05-01',
                'contract_enddt' => '2023-11-10',
                'contract_amount' => 6500000.00,
                'contract_payment' => 6500000.00,
                'contract_payment_dt' => '2023-11-25',
                'contract_payment_status' => 'Paid',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-018: Logistics Center South
            [
                'project_id' => 18,
                'contract_name' => 'Distribution Hub Construction',
                'contract_description' => 'Construction of distribution hub for southern region operations.',
                'contract_number' => 'CNT-2023-018-A',
                'contract_pic' => 'Helen Scott',
                'contractstatus_id' => 1,
                'contract_progress' => 60,
                'contract_dt' => '2023-07-20',
                'contract_startdt' => '2023-08-01',
                'contract_enddt' => '2024-06-30',
                'contract_amount' => 22000000.00,
                'contract_payment' => 13200000.00,
                'contract_payment_dt' => '2024-11-20',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 18,
                'contract_name' => 'Logistics Technology Systems',
                'contract_description' => 'Implementation of warehouse management and tracking systems.',
                'contract_number' => 'CNT-2023-018-B',
                'contract_pic' => 'Frank Bennett',
                'contractstatus_id' => 1,
                'contract_progress' => 45,
                'contract_dt' => '2023-07-25',
                'contract_startdt' => '2023-11-01',
                'contract_enddt' => '2024-06-15',
                'contract_amount' => 7500000.00,
                'contract_payment' => 3375000.00,
                'contract_payment_dt' => '2024-10-20',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-019: Luxury Hotel & Spa
            [
                'project_id' => 19,
                'contract_name' => 'Hotel Construction',
                'contract_description' => 'Construction of 5-star luxury hotel with 300 rooms and suites.',
                'contract_number' => 'CNT-2023-019-A',
                'contract_pic' => 'Jason Green',
                'contractstatus_id' => 1,
                'contract_progress' => 45,
                'contract_dt' => '2023-01-10',
                'contract_startdt' => '2023-01-20',
                'contract_enddt' => '2025-08-31',
                'contract_amount' => 120000000.00,
                'contract_payment' => 54000000.00,
                'contract_payment_dt' => '2024-11-25',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 19,
                'contract_name' => 'Spa & Wellness Facilities',
                'contract_description' => 'Construction of world-class spa and wellness center with premium amenities.',
                'contract_number' => 'CNT-2023-019-B',
                'contract_pic' => 'Victoria James',
                'contractstatus_id' => 1,
                'contract_progress' => 30,
                'contract_dt' => '2023-01-15',
                'contract_startdt' => '2023-08-01',
                'contract_enddt' => '2025-07-31',
                'contract_amount' => 35000000.00,
                'contract_payment' => 10500000.00,
                'contract_payment_dt' => '2024-10-15',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Contracts for PRJ-2023-020: Smart City Pilot
            [
                'project_id' => 20,
                'contract_name' => 'IoT Infrastructure Deployment',
                'contract_description' => 'Deployment of IoT sensors and smart city infrastructure across pilot zone.',
                'contract_number' => 'CNT-2023-020-A',
                'contract_pic' => 'Rachel Adams',
                'contractstatus_id' => 1,
                'contract_progress' => 55,
                'contract_dt' => '2023-09-05',
                'contract_startdt' => '2023-09-15',
                'contract_enddt' => '2024-12-31',
                'contract_amount' => 18000000.00,
                'contract_payment' => 9900000.00,
                'contract_payment_dt' => '2024-11-10',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => 20,
                'contract_name' => 'Smart City Platform Development',
                'contract_description' => 'Development of integrated smart city management platform and analytics.',
                'contract_number' => 'CNT-2023-020-B',
                'contract_pic' => 'Timothy Foster',
                'contractstatus_id' => 1,
                'contract_progress' => 65,
                'contract_dt' => '2023-09-10',
                'contract_startdt' => '2023-10-01',
                'contract_enddt' => '2024-11-30',
                'contract_amount' => 12000000.00,
                'contract_payment' => 7800000.00,
                'contract_payment_dt' => '2024-11-15',
                'contract_payment_status' => 'Partial',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('contracts')->insert($contracts);
    }
}
