<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $projects = [
            [
                'project_name' => 'Skyline Tower Construction',
                'project_description' => 'Construction of a 50-story residential tower in the city center.',
                'project_owner' => 'Skyline Developers Ltd.',
                'project_pic' => 'John Anderson',
                'project_number' => 'PRJ-2023-001',
                'project_startdt' => '2023-01-15',
                'project_enddt' => '2025-06-30',
                'project_address' => '123 Main St, Metropolis, NY',
                'project_latitude' => '40.7128',
                'project_longitude' => '-74.0060',
                'projectstatus_id' => 0, // Open
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Green Valley Estate Phase 1',
                'project_description' => 'Development of 100 luxury villas with eco-friendly features.',
                'project_owner' => 'Green Earth Homes',
                'project_pic' => 'Sarah Jenkins',
                'project_number' => 'PRJ-2023-002',
                'project_startdt' => '2023-03-01',
                'project_enddt' => '2024-12-15',
                'project_address' => '456 Oak Ave, Green Valley, CA',
                'project_latitude' => '34.0522',
                'project_longitude' => '-118.2437',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Harbor Bridge Maintenance',
                'project_description' => 'Structural reinforcement and repainting of the main harbor bridge.',
                'project_owner' => 'City Infrastructure Dept.',
                'project_pic' => 'Michael Ross',
                'project_number' => 'PRJ-2023-003',
                'project_startdt' => '2023-05-10',
                'project_enddt' => '2023-11-20',
                'project_address' => 'Harbor Bridge, Bay City, WA',
                'project_latitude' => '47.6062',
                'project_longitude' => '-122.3321',
                'projectstatus_id' => 1, // Closed
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Tech Hub HQ Renovation',
                'project_description' => 'Modernizing the headquarters for Tech Hub Inc. with smart office solutions.',
                'project_owner' => 'Tech Hub Inc.',
                'project_pic' => 'Emily Chen',
                'project_number' => 'PRJ-2023-004',
                'project_startdt' => '2023-06-01',
                'project_enddt' => '2024-02-28',
                'project_address' => '789 Tech Blvd, Silicon Valley, CA',
                'project_latitude' => '37.3875',
                'project_longitude' => '-122.0575',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Riverfront Park Development',
                'project_description' => 'Creating a public park with walking trails, playgrounds, and a community center.',
                'project_owner' => 'Metropolis Parks & Rec',
                'project_pic' => 'David Wilson',
                'project_number' => 'PRJ-2023-005',
                'project_startdt' => '2023-04-15',
                'project_enddt' => '2024-05-01',
                'project_address' => '101 River Rd, Metropolis, NY',
                'project_latitude' => '40.7306',
                'project_longitude' => '-73.9352',
                'projectstatus_id' => 3, // Pending
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Solar Farm Alpha',
                'project_description' => 'Installation of a 50MW solar power plant.',
                'project_owner' => 'Renewable Energy Corp',
                'project_pic' => 'Jessica Lee',
                'project_number' => 'PRJ-2023-006',
                'project_startdt' => '2023-02-20',
                'project_enddt' => '2023-12-31',
                'project_address' => 'Desert Rd, Sunnyville, AZ',
                'project_latitude' => '33.4484',
                'project_longitude' => '-112.0740',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Highway 101 Expansion',
                'project_description' => 'Widening of Highway 101 to add two new lanes.',
                'project_owner' => 'State Department of Transportation',
                'project_pic' => 'Robert Taylor',
                'project_number' => 'PRJ-2023-007',
                'project_startdt' => '2023-07-01',
                'project_enddt' => '2025-12-31',
                'project_address' => 'Highway 101, Coastal City, CA',
                'project_latitude' => '36.7783',
                'project_longitude' => '-119.4179',
                'projectstatus_id' => 2, // Canceled
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Metro Station North',
                'project_description' => 'Construction of a new underground metro station.',
                'project_owner' => 'City Transit Authority',
                'project_pic' => 'Amanda White',
                'project_number' => 'PRJ-2023-008',
                'project_startdt' => '2023-08-15',
                'project_enddt' => '2026-03-30',
                'project_address' => 'North Ave, Metropolis, NY',
                'project_latitude' => '40.7589',
                'project_longitude' => '-73.9851',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Ocean View Apartments',
                'project_description' => 'Building a complex of 200 seaside apartments.',
                'project_owner' => 'Coastal Living Properties',
                'project_pic' => 'Daniel Martin',
                'project_number' => 'PRJ-2023-009',
                'project_startdt' => '2023-09-01',
                'project_enddt' => '2025-05-15',
                'project_address' => '55 Ocean Dr, Miami, FL',
                'project_latitude' => '25.7617',
                'project_longitude' => '-80.1918',
                'projectstatus_id' => 1, // Closed
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Industrial Warehouse A',
                'project_description' => 'Construction of a large-scale logistics warehouse.',
                'project_owner' => 'Logistics Solutions Ltd.',
                'project_pic' => 'Thomas Clark',
                'project_number' => 'PRJ-2023-010',
                'project_startdt' => '2023-10-10',
                'project_enddt' => '2024-08-20',
                'project_address' => 'Industrial Park, Chicago, IL',
                'project_latitude' => '41.8781',
                'project_longitude' => '-87.6298',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Community Hospital Wing',
                'project_description' => 'Adding a new wing for pediatric care to the community hospital.',
                'project_owner' => 'HealthFirst Trust',
                'project_pic' => 'Karen Lewis',
                'project_number' => 'PRJ-2023-011',
                'project_startdt' => '2023-11-01',
                'project_enddt' => '2025-01-30',
                'project_address' => '200 Health Way, Houston, TX',
                'project_latitude' => '29.7604',
                'project_longitude' => '-95.3698',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'University Library Modernization',
                'project_description' => 'Upgrading the university library with digital archives and study pods.',
                'project_owner' => 'State University',
                'project_pic' => 'Brian Walker',
                'project_number' => 'PRJ-2023-012',
                'project_startdt' => '2023-05-20',
                'project_enddt' => '2024-04-15',
                'project_address' => 'University Campus, Boston, MA',
                'project_latitude' => '42.3601',
                'project_longitude' => '-71.0589',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Airport Terminal 3',
                'project_description' => 'Expansion of the international airport with a new terminal.',
                'project_owner' => 'National Airports Authority',
                'project_pic' => 'Steven Hall',
                'project_number' => 'PRJ-2023-013',
                'project_startdt' => '2023-01-10',
                'project_enddt' => '2027-12-31',
                'project_address' => 'Airport Rd, Denver, CO',
                'project_latitude' => '39.7392',
                'project_longitude' => '-104.9903',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Data Center X',
                'project_description' => 'Building a high-security data center for cloud services.',
                'project_owner' => 'CloudNet Systems',
                'project_pic' => 'Laura Allen',
                'project_number' => 'PRJ-2023-014',
                'project_startdt' => '2023-03-15',
                'project_enddt' => '2024-09-30',
                'project_address' => 'Tech Park, Ashburn, VA',
                'project_latitude' => '39.0438',
                'project_longitude' => '-77.4875',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Suburban Housing Phase 1',
                'project_description' => 'Development of affordable housing units in the suburbs.',
                'project_owner' => 'Community Housing Corp',
                'project_pic' => 'Kevin Young',
                'project_number' => 'PRJ-2023-015',
                'project_startdt' => '2023-06-20',
                'project_enddt' => '2024-11-30',
                'project_address' => 'Suburbia Dr, Atlanta, GA',
                'project_latitude' => '33.7490',
                'project_longitude' => '-84.3880',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Downtown Plaza Revamp',
                'project_description' => 'Redesigning the central city plaza with fountains and seating areas.',
                'project_owner' => 'City Beautification Committee',
                'project_pic' => 'Nancy King',
                'project_number' => 'PRJ-2023-016',
                'project_startdt' => '2023-04-01',
                'project_enddt' => '2023-10-31',
                'project_address' => 'Central Plaza, Seattle, WA',
                'project_latitude' => '47.6062',
                'project_longitude' => '-122.3321',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Wind Turbine Field',
                'project_description' => 'Installation of 20 wind turbines for renewable energy generation.',
                'project_owner' => 'WindPower Solutions',
                'project_pic' => 'Gary Wright',
                'project_number' => 'PRJ-2023-017',
                'project_startdt' => '2023-02-10',
                'project_enddt' => '2023-11-15',
                'project_address' => 'Windy Ridge, Oklahoma City, OK',
                'project_latitude' => '35.4676',
                'project_longitude' => '-97.5164',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Logistics Center South',
                'project_description' => 'A distribution hub for southern region operations.',
                'project_owner' => 'FastTrack Logistics',
                'project_pic' => 'Helen Scott',
                'project_number' => 'PRJ-2023-018',
                'project_startdt' => '2023-08-01',
                'project_enddt' => '2024-06-30',
                'project_address' => 'Distribution Way, Memphis, TN',
                'project_latitude' => '35.1495',
                'project_longitude' => '-90.0490',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Luxury Hotel & Spa',
                'project_description' => 'Construction of a 5-star hotel and wellness spa.',
                'project_owner' => 'Grand Hotels Group',
                'project_pic' => 'Jason Green',
                'project_number' => 'PRJ-2023-019',
                'project_startdt' => '2023-01-20',
                'project_enddt' => '2025-08-31',
                'project_address' => 'Resort Blvd, Las Vegas, NV',
                'project_latitude' => '36.1699',
                'project_longitude' => '-115.1398',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_name' => 'Smart City Pilot',
                'project_description' => 'Implementing IoT infrastructure for a smart city pilot zone.',
                'project_owner' => 'Future City Tech',
                'project_pic' => 'Rachel Adams',
                'project_number' => 'PRJ-2023-020',
                'project_startdt' => '2023-09-15',
                'project_enddt' => '2024-12-31',
                'project_address' => 'Innovation District, Austin, TX',
                'project_latitude' => '30.2672',
                'project_longitude' => '-97.7431',
                'projectstatus_id' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('projects')->insert($projects);

    }
}
