<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VendorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Clear existing data
        DB::table('vendors')->truncate();

        $vendors = [
            [
                'vendortype_id' => 1,
                'vendor_code' => 'VND-0001',
                'vendor_name' => 'PT. Sumber Material',
                'vendor_description' => 'Supplier for general construction materials',
                'vendor_email' => 'info@sumbermaterial.co.id',
                'vendor_phone' => '021-555-0101',
                'vendor_address' => 'Jl. Raya No. 1, Jakarta',
                'vendor_city' => 'Jakarta',
                'vendor_state' => 'DKI Jakarta',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 2,
                'vendor_code' => 'VND-0002',
                'vendor_name' => 'CV. Kontraktor Nusantara',
                'vendor_description' => 'General contractor and subcontractor services',
                'vendor_email' => 'contact@kontraktornusantara.com',
                'vendor_phone' => '021-555-0202',
                'vendor_address' => 'Jl. Industri No. 5, Bandung',
                'vendor_city' => 'Bandung',
                'vendor_state' => 'Jawa Barat',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 7,
                'vendor_code' => 'VND-0003',
                'vendor_name' => 'PT. Logistik Prima',
                'vendor_description' => 'Logistics and transportation services',
                'vendor_email' => 'ops@logistikprima.co.id',
                'vendor_phone' => '021-555-0303',
                'vendor_address' => 'Jl. Pelabuhan No. 2, Surabaya',
                'vendor_city' => 'Surabaya',
                'vendor_state' => 'Jawa Timur',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 3,
                'vendor_code' => 'VND-0004',
                'vendor_name' => 'PT. Beton Jaya',
                'vendor_description' => 'Concrete supplier',
                'vendor_email' => 'sales@betonjaya.com',
                'vendor_phone' => '021-555-0404',
                'vendor_address' => 'Jl. Semen No. 8, Jakarta',
                'vendor_city' => 'Jakarta',
                'vendor_state' => 'DKI Jakarta',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 4,
                'vendor_code' => 'VND-0005',
                'vendor_name' => 'CV. Baja Mandiri',
                'vendor_description' => 'Steel reinforcement',
                'vendor_email' => 'order@bajamandiri.co.id',
                'vendor_phone' => '021-555-0505',
                'vendor_address' => 'Jl. Besi No. 12, Bekasi',
                'vendor_city' => 'Bekasi',
                'vendor_state' => 'Jawa Barat',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 5,
                'vendor_code' => 'VND-0006',
                'vendor_name' => 'PT. Elektrik Sejahtera',
                'vendor_description' => 'Electrical components',
                'vendor_email' => 'support@elektriksejahtera.com',
                'vendor_phone' => '021-555-0606',
                'vendor_address' => 'Jl. Listrik No. 3, Tangerang',
                'vendor_city' => 'Tangerang',
                'vendor_state' => 'Banten',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 6,
                'vendor_code' => 'VND-0007',
                'vendor_name' => 'CV. Pipa Air',
                'vendor_description' => 'Plumbing supplies',
                'vendor_email' => 'sales@pipaair.co.id',
                'vendor_phone' => '021-555-0707',
                'vendor_address' => 'Jl. Air No. 9, Bogor',
                'vendor_city' => 'Bogor',
                'vendor_state' => 'Jawa Barat',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 1,
                'vendor_code' => 'VND-0008',
                'vendor_name' => 'PT. Cat Warna Warni',
                'vendor_description' => 'Paint and coatings',
                'vendor_email' => 'info@catwarnawarni.com',
                'vendor_phone' => '021-555-0808',
                'vendor_address' => 'Jl. Warna No. 4, Jakarta',
                'vendor_city' => 'Jakarta',
                'vendor_state' => 'DKI Jakarta',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 2,
                'vendor_code' => 'VND-0009',
                'vendor_name' => 'CV. Kayu Jati',
                'vendor_description' => 'Timber and wood',
                'vendor_email' => 'order@kayujati.co.id',
                'vendor_phone' => '021-555-0909',
                'vendor_address' => 'Jl. Hutan No. 7, Jepara',
                'vendor_city' => 'Jepara',
                'vendor_state' => 'Jawa Tengah',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 3,
                'vendor_code' => 'VND-0010',
                'vendor_name' => 'PT. Kaca Bening',
                'vendor_description' => 'Glass and windows',
                'vendor_email' => 'sales@kacabening.com',
                'vendor_phone' => '021-555-1010',
                'vendor_address' => 'Jl. Transparan No. 5, Bandung',
                'vendor_city' => 'Bandung',
                'vendor_state' => 'Jawa Barat',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 4,
                'vendor_code' => 'VND-0011',
                'vendor_name' => 'CV. Atap Kuat',
                'vendor_description' => 'Roofing materials',
                'vendor_email' => 'order@atapkuat.co.id',
                'vendor_phone' => '021-555-1111',
                'vendor_address' => 'Jl. Genteng No. 6, Surabaya',
                'vendor_city' => 'Surabaya',
                'vendor_state' => 'Jawa Timur',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 5,
                'vendor_code' => 'VND-0012',
                'vendor_name' => 'PT. Lantai Indah',
                'vendor_description' => 'Flooring and tiles',
                'vendor_email' => 'info@lantaiindah.co.id',
                'vendor_phone' => '021-555-1212',
                'vendor_address' => 'Jl. Keramik No. 2, Semarang',
                'vendor_city' => 'Semarang',
                'vendor_state' => 'Jawa Tengah',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 8,
                'vendor_code' => 'VND-0013',
                'vendor_name' => 'CV. Taman Asri',
                'vendor_description' => 'Landscaping services',
                'vendor_email' => 'contact@tamanasri.co.id',
                'vendor_phone' => '021-555-1313',
                'vendor_address' => 'Jl. Bunga No. 11, Malang',
                'vendor_city' => 'Malang',
                'vendor_state' => 'Jawa Timur',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 9,
                'vendor_code' => 'VND-0014',
                'vendor_name' => 'PT. Alat Berat',
                'vendor_description' => 'Heavy machinery rental',
                'vendor_email' => 'rental@alatberat.co.id',
                'vendor_phone' => '021-555-1414',
                'vendor_address' => 'Jl. Traktor No. 1, Balikpapan',
                'vendor_city' => 'Balikpapan',
                'vendor_state' => 'Kalimantan Timur',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 1,
                'vendor_code' => 'VND-0015',
                'vendor_name' => 'CV. Pasir Halus',
                'vendor_description' => 'Sand and aggregates',
                'vendor_email' => 'order@pasirhalus.co.id',
                'vendor_phone' => '021-555-1515',
                'vendor_address' => 'Jl. Pantai No. 10, Cirebon',
                'vendor_city' => 'Cirebon',
                'vendor_state' => 'Jawa Barat',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 3,
                'vendor_code' => 'VND-0016',
                'vendor_name' => 'PT. Semen Tiga Roda',
                'vendor_description' => 'Cement distributor',
                'vendor_email' => 'sales@sementiga.co.id',
                'vendor_phone' => '021-555-1616',
                'vendor_address' => 'Jl. Beton No. 15, Cibinong',
                'vendor_city' => 'Cibinong',
                'vendor_state' => 'Jawa Barat',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 2,
                'vendor_code' => 'VND-0017',
                'vendor_name' => 'CV. Paku Payung',
                'vendor_description' => 'Fasteners and hardware',
                'vendor_email' => 'order@pakupayung.co.id',
                'vendor_phone' => '021-555-1717',
                'vendor_address' => 'Jl. Bengkel No. 14, Medan',
                'vendor_city' => 'Medan',
                'vendor_state' => 'Sumatera Utara',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 5,
                'vendor_code' => 'VND-0018',
                'vendor_name' => 'PT. Cahaya Lampu',
                'vendor_description' => 'Lighting fixtures',
                'vendor_email' => 'info@cahayalampu.com',
                'vendor_phone' => '021-555-1818',
                'vendor_address' => 'Jl. Terang No. 8, Palembang',
                'vendor_city' => 'Palembang',
                'vendor_state' => 'Sumatera Selatan',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 2,
                'vendor_code' => 'VND-0019',
                'vendor_name' => 'CV. Pintu Geser',
                'vendor_description' => 'Doors and frames',
                'vendor_email' => 'sales@pintugeser.co.id',
                'vendor_phone' => '021-555-1919',
                'vendor_address' => 'Jl. Kayu No. 3, Makassar',
                'vendor_city' => 'Makassar',
                'vendor_state' => 'Sulawesi Selatan',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'vendortype_id' => 1,
                'vendor_code' => 'VND-0020',
                'vendor_name' => 'PT. Solusi Bangunan',
                'vendor_description' => 'General building supplies',
                'vendor_email' => 'info@solusibangun.co.id',
                'vendor_phone' => '021-555-2020',
                'vendor_address' => 'Jl. Proyek No. 99, Jakarta',
                'vendor_city' => 'Jakarta',
                'vendor_state' => 'DKI Jakarta',
                'vendor_country' => 'Indonesia',
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('vendors')->insert($vendors);
    }
}
